# Generated by Django 4.1.5 on 2023-01-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseboatapp', '0015_alter_addroom_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addboat',
            fields=[
                ('id', models.IntegerField()),
                ('boat_id', models.IntegerField(primary_key='True', serialize=False)),
                ('boat_name', models.CharField(max_length=100, verbose_name='room_name')),
                ('boat_type', models.CharField(max_length=20, verbose_name='room_type')),
                ('image', models.ImageField(upload_to='images/', verbose_name='image')),
                ('rate', models.CharField(max_length=100, verbose_name='rate')),
                ('discription', models.CharField(max_length=25, verbose_name='discription')),
                ('phone', models.IntegerField()),
                ('location', models.TextField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Addroom',
        ),
    ]
