# Generated by Django 4.0.8 on 2023-01-11 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseboatapp', '0016_addboat_delete_addroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addboat',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
