# Generated by Django 4.0.8 on 2023-01-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houseboatapp', '0017_delete_addboat_delete_login_delete_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addboat',
            fields=[
                ('id', models.IntegerField()),
                ('boat_id', models.IntegerField(primary_key='True', serialize=False)),
                ('boat_name', models.CharField(max_length=100, verbose_name='room_name')),
                ('boat_type', models.CharField(max_length=20, verbose_name='room_type')),
                ('image', models.ImageField(upload_to='images/', verbose_name='image')),
                ('rate', models.CharField(max_length=100, verbose_name='rate')),
                ('discription', models.CharField(max_length=25, verbose_name='discription')),
                ('phone', models.IntegerField()),
                ('location', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('Transaction_id', models.IntegerField()),
                ('Status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('phone', models.TextField(max_length=10)),
                ('password', models.CharField(max_length=25)),
                ('usertype', models.CharField(default='s', max_length=25)),
            ],
        ),
    ]
