# Generated by Django 3.2.17 on 2023-02-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseboatapp', '0018_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='id',
        ),
        migrations.AlterField(
            model_name='registration',
            name='reg_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
